#!/bin/bash
#
# Submit SLURM job array to prepare real data for inpainter fine-tuning.
# Each array task processes one day's worth of runs (up to 20) through
# PrepareRealDataInpainter.C, combining them into a single output ROOT file.
#
# Usage:
#   bash macro/submit_prepare_realdata.sh <runlist.txt> <days_manifest.txt> [output_dir]
#
# Input files (generated by generate_realdata_runlist.py):
#   runlist.txt        Two-column file: <run_number> <file_path>
#   days_manifest.txt  Three-column file: <date> <start_idx> <count>
#
# Environment variables:
#   PARTITION     - SLURM partition (default: meg-short)
#   ANALYZER_DIR  - Path to meganalyzer (default: $HOME/meghome/offline/analyzer)
#   START_FROM    - Skip the first N days (default: 0)
#
# Output: one ROOT file per day in output_dir/DataGammaAngle_YYYY-MM-DD.root
#

set -euo pipefail
cd "$(dirname "$0")/.."

if [ $# -lt 2 ]; then
    echo "Usage: $0 <runlist.txt> <days_manifest.txt> [output_dir]"
    echo ""
    echo "  runlist.txt        Two-column file: <run_number> <file_path>"
    echo "  days_manifest.txt  Three-column file: <date> <start_idx> <count>"
    echo "  output_dir         Output directory (default: data/real_data/raw/)"
    echo ""
    echo "Environment variables:"
    echo "  START_FROM    Skip first N days (default: 0)"
    echo "  PARTITION     SLURM partition (default: meg-short)"
    exit 1
fi

RUNLIST="$(realpath "$1")"
DAYS_MANIFEST="$(realpath "$2")"
OUTPUT_DIR="${3:-data/real_data/raw}"
OUTPUT_DIR="$(realpath -m "$OUTPUT_DIR")"
PARTITION="${PARTITION:-meg-short}"
START_FROM="${START_FROM:-0}"

case "$PARTITION" in
    meg-long|meg-short|mu3e) ACCOUNT_LINE="#SBATCH --account=meg" ;;
    *)                       ACCOUNT_LINE="" ;;
esac

# Count valid (non-comment, non-empty) lines in day manifest
N_TOTAL_DAYS=$(grep -cvE '^\s*($|#)' "$DAYS_MANIFEST")

if [ "$N_TOTAL_DAYS" -le 0 ]; then
    echo "[ERROR] No valid entries in day manifest"
    exit 1
fi

# Apply START_FROM offset
N_DAYS=$((N_TOTAL_DAYS - START_FROM))
if [ "$N_DAYS" -le 0 ]; then
    echo "[ERROR] START_FROM=${START_FROM} >= total days ${N_TOTAL_DAYS}"
    exit 1
fi

echo "[INFO] Run list: ${RUNLIST}"
echo "[INFO] Day manifest: ${DAYS_MANIFEST}"
echo "[INFO] Total days: ${N_TOTAL_DAYS}, starting from: ${START_FROM}, remaining: ${N_DAYS}"
echo "[INFO] Output: ${OUTPUT_DIR}"
echo "[INFO] Partition: ${PARTITION}"

mkdir -p log "$OUTPUT_DIR"

# Meganalyzer path (must cd to analyzer dir before running)
ANALYZER_DIR="${ANALYZER_DIR:-$HOME/meghome/offline/analyzer}"
MACRO_PATH="$HOME/meghome/xec-ml-wl/macro/PrepareRealDataInpainter.C"

# Submit in chunks of 2000 (SLURM max array size, indices 0-1999)
MAX_ARRAY=2000
N_CHUNKS=$(( (N_DAYS + MAX_ARRAY - 1) / MAX_ARRAY ))
SUBMITTED=0

mkdir -p "$HOME/.cache/xec-ml-wl"

for ((CHUNK=0; CHUNK<N_CHUNKS; CHUNK++)); do
    GLOBAL_START=$((CHUNK * MAX_ARRAY))
    GLOBAL_END=$(( (CHUNK + 1) * MAX_ARRAY - 1 ))
    if [ $GLOBAL_END -ge $N_DAYS ]; then
        GLOBAL_END=$((N_DAYS - 1))
    fi
    CHUNK_SIZE=$(( GLOBAL_END - GLOBAL_START + 1 ))
    ARRAY_END=$(( CHUNK_SIZE - 1 ))

    BATCH_SCRIPT=$(mktemp "$HOME/.cache/xec-ml-wl/prepare_realdata_chunk${CHUNK}_XXXXXX.sh")

    cat > "${BATCH_SCRIPT}" << SLURM_EOF
#!/bin/bash
${ACCOUNT_LINE}
#SBATCH --partition=${PARTITION}
#SBATCH --time=1:00:00
#SBATCH --hint=nomultithread
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=3700
#SBATCH --job-name=prep_real
#SBATCH --array=0-${ARRAY_END}
#SBATCH --output=$HOME/meghome/xec-ml-wl/log/prep_real_%A_%a.log

START_FROM=${START_FROM}
CHUNK_OFFSET=${GLOBAL_START}

echo "=== PrepareRealData: task \${SLURM_ARRAY_TASK_ID} ==="
echo "Host: \$(hostname)"
echo "Date: \$(date)"
echo ""

# Read the day manifest line for this task
DAY_IDX=\$(( START_FROM + CHUNK_OFFSET + SLURM_ARRAY_TASK_ID ))

# Extract the line from the day manifest (skip comments)
LINE=\$(grep -vE '^\s*($|#)' "${DAYS_MANIFEST}" | sed -n "\$((DAY_IDX + 1))p")

if [ -z "\${LINE}" ]; then
    echo "[ERROR] Day index \${DAY_IDX} out of range"
    exit 1
fi

DATE_LABEL=\$(echo "\${LINE}" | awk '{print \$1}')
START_IDX=\$(echo "\${LINE}" | awk '{print \$2}')
N_FILES=\$(echo "\${LINE}" | awk '{print \$3}')

echo "Day: \${DATE_LABEL}, runlist start_idx: \${START_IDX}, count: \${N_FILES}"
echo ""

cd ${ANALYZER_DIR}
mkdir -p "\$HOME/.cache/xec-ml-wl"

LOADER="\$HOME/.cache/xec-ml-wl/prep_real_loader_\${SLURM_ARRAY_JOB_ID}_\${SLURM_ARRAY_TASK_ID}.C"
FUNC_NAME="prep_real_loader_\${SLURM_ARRAY_JOB_ID}_\${SLURM_ARRAY_TASK_ID}"
cat > "\${LOADER}" <<MACRO_EOF
void \${FUNC_NAME}() {
    gROOT->ProcessLine(".L ${MACRO_PATH}+");
    gROOT->ProcessLine("PrepareRealDataInpainterFromListRange(\"${RUNLIST}\", \${START_IDX}, \${N_FILES}, \"${OUTPUT_DIR}\", \"\${DATE_LABEL}\")");
}
MACRO_EOF

./meganalyzer -b -q -I "\${LOADER}()"
rm -f "\${LOADER}"

echo ""
echo "=== Done: \$(date) ==="
SLURM_EOF

    echo "[INFO] Chunk $((CHUNK+1))/${N_CHUNKS}: ${CHUNK_SIZE} tasks (days ${GLOBAL_START}-${GLOBAL_END})"
    echo "[INFO] Batch script: ${BATCH_SCRIPT}"
    sbatch "${BATCH_SCRIPT}"
    SUBMITTED=$((SUBMITTED + CHUNK_SIZE))
    echo ""
    sleep 1
done

echo "[INFO] Submitted ${SUBMITTED} tasks in ${N_CHUNKS} chunk(s)"
echo "[INFO] Each task processes one day's runs into a single ROOT file"
