// Author: Rina Onda

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// MEGTXECEnePMWeight                                                         //
//                                                                            //
// Begin_Html <!--
/*-->

Description:
<p>
Calculate channely by channel energy correction parameters.
</p>

<!--*/
// --> End_Html
//                                                                            //
// The event methods have been written by Rina Onda.                          //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     EventHeader                                                            //
//     XECRunHeader                                                           //
//     XECPMRunHeader                                                         //
//     XECPM                                                                  //
//     XECPMCluster                                                           //
//     XECEnePMWeightResult                                                   //
//     XECEnePMWeightCorrection                                               //
//     XECEnePMWeightFaceCorrection                                           //
//     XECFastRecResult                                                       //
//     XECPosLocalFitResult                                                   //
//     XECEneTotalSumRecCorrection                                            //
//     XECEneTotalSumRecScaleCorrection                                       //
//     XECTimeFitResult                                                       //
//     XECPileupResult                                                        //
//     XECPileupClusteringResult                                              //
//     MCXECHit                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/MEGTXECEnePMWeightGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////
// $Id$

// temporarily disable warnings caused by various header file under Visual C++
#include <RConfig.h>
#if defined( R__VISUAL_CPLUSPLUS )
#pragma warning( push )
#pragma warning( disable : 4244 )
#pragma warning( disable : 4800 )
#endif // R__VISUAL_CPLUSPLUS
#include <TROOT.h>
#include <TMath.h>
#include <TTree.h>
#include <TChain.h>
#include <TGraphSmooth.h>
#include <TF1.h>
#include <TStyle.h>
#include <TColor.h>
#include <TCanvas.h>
#include <TPostScript.h>
#include <TPaveText.h>
#include <TSpline.h>
#if defined( R__VISUAL_CPLUSPLUS )
#pragma warning( pop )
#endif // R__VISUAL_CPLUSPLUS
#include "tasks/MEGTXECEnePMWeight.h"
#include "tasks/MEGTXEC.h"
#include "generated/MEGTXECPosLocalFit_Base.h"
#include "xec/xectools.h"
#include "constants/xec/xecconst.h"
#include "xec/PMSolidAngle.h"
#include "xec/XECGetPMList.h"
#include "generated/MEGAnalyzer.h"
#include "ROMEiostream.h"
#include "ROMESQLDataBase.h"
#include "ROMEAnalyzer.h"

#ifdef HAVE_LIBTORCH
// ROOT defines ClassDef(name,id) as a 2-arg macro which conflicts with
// torch::jit::ClassDef class in tree_views.h.
// LibTorch includes and restore it afterward.
#pragma push_macro("ClassDef")
#undef ClassDef
#include <torch/script.h>
#include <torch/torch.h>
#pragma pop_macro("ClassDef")
#endif

// uncomment if you want to include headers of all folders
//#include "MEGAllFolders.h"

ClassImp(MEGTXECEnePMWeight)

namespace XECNPHOESTIMATION
{
std::map<XECNphoEstimation::TableCacheKey, XECNphoEstimation*> gvNphoEstimation;
}


namespace
{
std::vector<MEGTXECEnePMWeight::RecGamma*> fvRecGamma;
std::vector<MEGTXECEnePMWeight::PLGamma*> fvPLGamma;
XECLDTemplateTable* fLDTemplateTable = 0;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::Init()
{
   // Initialization
   if (GetSP()->GetMakeTemplate()->GetActive()) {
      PrepareTemplate();
   }

   // Read trigger mask
   fTRGMask.clear();
   TObjArray *maskArray = GetSP()->GetTRGMask().Tokenize(",");
   if (!maskArray->GetEntries()) {
      maskArray = gAnalyzer->GetXECTask()->GetSP()->GetTRGMask().Tokenize(",");
   }
   for (Int_t iMask = 0; iMask < maskArray->GetEntries(); iMask++) {
      TObjString *mask = (TObjString*)maskArray->At(iMask);
      fTRGMask.push_back((Short_t)mask->GetString().Atoi());
   }
   delete maskArray;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::BeginOfRun()
{
   const Int_t nPM = gAnalyzer->GetXECRunHeader()->GetNPM();
   if (nPM <= 0) {
      return;
   }

   //Get parameter for DCR from SP
   if (GetSP()->GetDeadChannelRecovery()->GetMethod() > -0.99){
      gAnalyzer->GetXECEnePMWeightCorrection()->SetDeadChannelRecoveryFlag(GetSP()->GetDeadChannelRecovery()->GetMethod());
   }
   if (GetSP()->GetDeadChannelRecovery()->Getdistance_threshold() > -0.99){
      gAnalyzer->GetXECEnePMWeightCorrection()->SetDeadChannelRecoveryDistanceThreshold(GetSP()->GetDeadChannelRecovery()->Getdistance_threshold());
   }
   if (GetSP()->GetDeadChannelRecovery()->Getnpho_threshold() > -0.99){
      gAnalyzer->GetXECEnePMWeightCorrection()->SetDeadChannelRecoveryNphoThreshold(GetSP()->GetDeadChannelRecovery()->Getnpho_threshold());
   }


   if (GetSP()->GetSolidAngleCorrection()->GetActive()) {
      GetSolidAngleCorrFunc();
   }

   if (GetSP()->GetFaceCorrection()->GetActive()) {
      GetFaceCorrFunc();
   }

   if (gAnalyzer->GetXECEnePMWeightCorrection()->GetDeadChannelRecoveryFlag() == kRecoverFromTemplate) {
      GetLDTemplateTable();
   }

#ifdef HAVE_LIBTORCH
   if (gAnalyzer->GetXECEnePMWeightCorrection()->GetDeadChannelRecoveryFlag() == kRecoverFromMLInpainting) {
      TString modelPath = GetSP()->GetMLInpainter()->GetModelPath();
      gSystem->ExpandPathName(modelPath);
      try {
         auto* model = new torch::jit::Module(torch::jit::load(modelPath.Data()));
         model->eval();
         torch::set_num_threads(1);
         torch::set_num_interop_threads(1);
         fInpainterModel = static_cast<void*>(model);
         Report(R_INFO, "ML inpainter model loaded from %s", modelPath.Data());
      } catch (const c10::Error& e) {
         Report(R_ERROR, "Failed to load ML inpainter model from %s: %s", modelPath.Data(), e.what());
         fInpainterModel = nullptr;
      }
   }
#endif
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::Event()
{
   const Int_t nPM = gAnalyzer->GetXECRunHeader()->GetNPM();
   if (nPM <= 0) {
      return;
   }
   
   if (!EventSelection()) {
      return;
   }

   Release();

   Int_t nGamma;
   if (1) {
      //currently only one gamma is assumed.
      //if (gAnalyzer->GetXECPMAt(0)->Getfsize() > 1) {
      nGamma = 1;
   } else {
      nGamma = 0;
   }

   MEGXECEnePMWeightResult* pEnePMWeightResult;
   for (Int_t iPM = 0; iPM < nPM; iPM++) {
      pEnePMWeightResult = gAnalyzer->GetXECEnePMWeightResultAt(iPM);
      pEnePMWeightResult->SetweightSize(nGamma);
      pEnePMWeightResult->Setcharge2nphoSize(nGamma);
      pEnePMWeightResult->SetsolidangleSize(nGamma);
      pEnePMWeightResult->SetsolidanglecorrSize(nGamma);
      pEnePMWeightResult->SetfacecorrSize(nGamma);
      pEnePMWeightResult->SetdeadcorrSize(nGamma);
      pEnePMWeightResult->SetnphoSize(nGamma);
      pEnePMWeightResult->SetnphofitSize(nGamma);
      pEnePMWeightResult->SetnphorecoveredSize(nGamma);
   }

   MEGXECPMRunHeader* pmrh;
   for (Int_t iGamma = 0; iGamma < nGamma; iGamma++) {
      RecGamma* gamma = new RecGamma(iGamma, nPM);
      for (Int_t iPM = 0; iPM < nPM; iPM++) {
         pmrh = gAnalyzer->GetXECPMRunHeaderAt(iPM);
         gamma->fvPM[iPM] = new PM();
         gamma->fvPM[iPM]->fIndex = iPM;
         gamma->fvPM[iPM]->fPMRH = pmrh;
         gamma->fvPM[iPM]->fNpho = gAnalyzer->GetXECPMClusterAt(iPM)->GetnphoAt(iGamma);
         // std::cout<<iPM<<" Npho : "<<gamma->fvPM[iPM]->fNpho<<std::endl;
         gamma->fvPM[iPM]->fInvalid = gAnalyzer->GetXECPMClusterAt(iPM)->GetinvalidAt(iGamma);
         Double_t conv_factor = pmrh->GetGain() * pmrh->GetWDGain()
                                * pmrh->GetQE() * pmrh->GetCE()
                                * pmrh->GetCTAP() * MEG::eplus;
         if (!gamma->fvPM[iPM]->fInvalid && conv_factor != 0) {
            gamma->fvPM[iPM]->fCharge2Npho = 1. / conv_factor;
         }
      }
      gamma->fMaxPMInner = GetMaxPMInner(iGamma, gamma->fvPM);
      gamma->fEnergy = GetGammaEnergy(iGamma, gamma->fvPM);//rough estimation

      if (GetSP()->GetSolidAngleCorrection()->GetActive()) {
         CalcSolidAngleCorrection(iGamma, gamma);
      }

      if (GetSP()->GetFaceCorrection()->GetActive()) {
         CalcFaceCorrection(iGamma, gamma);
      }

      if (gAnalyzer->GetXECEnePMWeightCorrection()->GetDeadChannelRecoveryFlag()) {
         RecoverDeadChannel(iGamma, gamma);
      }

      fvRecGamma.push_back(gamma);
   }


   // fill the results to the folder
   for (auto gamma : fvRecGamma) {

      // calculate weight combining the corrections above
      CalcWeight(gamma);

      // fill results to folder
      FillResult(gamma);
   }

   if (GetSP()->GetMakeTemplate()->GetActive()) {
      if (fvRecGamma.size() > 0) {
         AddTemplate(fvRecGamma[0]);
      }
   }
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::EndOfRun()
{
   //Delete objects
   if (fSolidAngleCorrFunc) {
      delete fSolidAngleCorrFunc;
   }
   fSolidAngleCorrFunc = 0;
   SafeDelete(fSolidAngleCorrFuncCoeff);

   for (auto func : fvFaceCorrFunc) {
      delete func;
   }
   fvFaceCorrFunc.clear();

#ifdef HAVE_LIBTORCH
   if (fInpainterModel) {
      delete static_cast<torch::jit::Module*>(fInpainterModel);
      fInpainterModel = nullptr;
   }
#endif

   Release();
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::Terminate()
{
   if (GetSP()->GetMakeTemplate()->GetActive()) {
      //assuming geometry in PMRunHeader does not chanege during the runs.
      for (auto tmpl : fLDTemplateTable->GetLDTemplateList()) {
         tmpl->GetPMInfo()->SetPM(gAnalyzer->GetXECPMRunHeaders());
      }
      TString fileName = Form("XECLDTemplate%d.root", (int)gAnalyzer->GetCurrentRunNumber());
      fLDTemplateTable->ExportTable(fileName);
   }

   XECNPHOESTIMATION::gvNphoEstimation.clear();
   if (fLDTemplateTable) {
      delete fLDTemplateTable;
   }
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::Release()
{
   for (auto gamma : fvRecGamma) {
      delete gamma;
   }
   fvRecGamma.clear();
   for (auto gamma : fvPLGamma) {
      delete gamma;
   }
   fvPLGamma.clear();
}

//______________________________________________________________________________
Bool_t MEGTXECEnePMWeight::EventSelection()
{
   if (fTRGMask.size()) {
      auto mask = gAnalyzer->GetEventHeader()->Getmask();
      if (std::find(fTRGMask.begin(), fTRGMask.end(), mask) != fTRGMask.end()) {
         return false;
      }
   }

   return true;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::CalcSolidAngleCorrection(Int_t iGamma, RecGamma* gamma)
{
   if (!GetPosition(iGamma, gamma)) {
      Report(R_WARNING, "Position of %d-th gamma is not found. Solid angle correction is skipped.\n", iGamma);
      return;
   }

   MEGXECEnePMWeightCorrection *pCorrection = gAnalyzer->GetXECEnePMWeightCorrection();
   if (gamma->fUVW[2] > pCorrection->GetSolidAngleCorrDepthBoundary()) {
      return;
   }

   fSolidAngleMaxInner = GetSolidAngle(gamma->fXYZ, gamma->fMaxPMInner);

   Float_t factor;
   switch (pCorrection->GetSolidAngleCorrType()) {
   case kSolidAngleNoCorrection :
   default :
      factor = 1;
      break;
   case kSolidAngleCorrWithPol :
      factor = GetSolidAngleCorrFactor(fSolidAngleMaxInner);
      break;
   case kSolidAngleCorrWithLog :
      fSolidAngleCorrFunc->SetParameter(1, fSolidAngleCorrFuncCoeff->Eval(gamma->fUVW[2]));
      factor = GetSolidAngleCorrFactor(fSolidAngleMaxInner);
      break;
   }

   //only inner PMs are corrected.
   for (auto pm : gamma->fvPM) {
      if (pm->fPMRH->GetFace() == XECCONSTANTS::kInnerFace) {
         pm->fSolidAngle = fSolidAngleMaxInner;
         pm->fSolidAngleCorr = factor;
      }
   }
}

//______________________________________________________________________________
Float_t MEGTXECEnePMWeight::GetSolidAngle(std::array<Float_t, 3>& xyz, const Int_t pmIndex)
{

   MEGXECPMRunHeader* pmrh = gAnalyzer->GetXECPMRunHeaderAt(pmIndex);

   TVector3 view(xyz[0], xyz[1], xyz[2]);
   TVector3 pos;
   TVector3 dir;
   pos.SetXYZ(pmrh->GetXYZAt(0), pmrh->GetXYZAt(1), pmrh->GetXYZAt(2));
   dir.SetXYZ(pmrh->GetDirectionAt(0), pmrh->GetDirectionAt(1), pmrh->GetDirectionAt(2));

   if (pmrh->GetIsSiPM()) {
      return PMSolidAngle::PMSolidAngleMPPC(view, pos, dir) * 4 * TMath::Pi();
   } else {
      return PMSolidAngle::PMSolidAnglePMT(view, pos, dir) * 4 * TMath::Pi();
   }
}

//______________________________________________________________________________
Float_t MEGTXECEnePMWeight::GetSolidAngleCorrFactor(Float_t solidAngle, Option_t *opt)
{
   // Correction of shallow event by solid angle (maximum solid angle for inner PMTs)
   if (!fSolidAngleCorrFunc) {
      return 1;
   }

   TString option = opt;
   option.ToUpper();

   Float_t factor = fSolidAngleCorrFunc->Eval(solidAngle);
   if (factor > 0) {
      factor = fSolidAngleCorrFuncNorm / factor;
   } else {
      factor = 1;
   }
   return factor;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::CalcFaceCorrection(const Int_t iGamma, RecGamma* gamma)
{
   if (!GetPosition(iGamma, gamma)) {
      Report(R_WARNING, "Position of %d-th gamma is not found. Face correction is skipped.\n", iGamma);
      return;
   }

   MEGXECEnePMWeightCorrection *pCorrection = gAnalyzer->GetXECEnePMWeightCorrection();
   switch (pCorrection->GetFaceCorrType()) {
   case kFaceNoCorrection :
   default :
      break;
   case kFaceCorrFaceByFace :
      std::vector<Float_t> vFactor = GetFaceCorrFactor(gamma->fUVW);
      for (auto pm : gamma->fvPM) {
         pm->fFaceCorr = vFactor[pm->fPMRH->GetFace()];
      }
      break;
   }
}

//______________________________________________________________________________
std::vector<Float_t> MEGTXECEnePMWeight::GetFaceCorrFactor(const Float_t u, const Float_t v, const Float_t w)
{
   std::vector<Float_t> vFactor(XECCONSTANTS::kNumberOfFaces, 1.);
   const Int_t group[XECCONSTANTS::kNumberOfFaces] = {0, 1, 2, 2, 3, 3};
   const Int_t sign[3][XECCONSTANTS::kNumberOfFaces] = {{1, 1, 1, -1, 1, 1}, {1, 1, 1, 1, 1, -1}, {1, 1, 1, 1, 1, 1}};

   Float_t ucor, vcor, wcor;
   if (u == XECTOOLS::kXECInvalidU ||
       v == XECTOOLS::kXECInvalidV ||
       w == XECTOOLS::kXECInvalidW) {
      ucor = 0;
      vcor = 0;
      wcor = 0;
   } else {
      ucor = u;
      vcor = v;
      wcor = w;
   }

   for (Int_t iFace = 0; iFace < XECCONSTANTS::kNumberOfFaces; iFace++) {
      Float_t factor = 1;
      if (fvFaceCorrFunc.size() == 8) {
         factor *= fvFaceCorrFunc[group[iFace] * 2] ? TMath::Max(0., fvFaceCorrFunc[group[iFace] * 2]->Eval(ucor * sign[0][iFace])) : 1;
         factor *= fvFaceCorrFunc[group[iFace] * 2 + 1] ? TMath::Max(0., fvFaceCorrFunc[group[iFace] * 2 + 1]->Eval(vcor * sign[1][iFace])) : 1;
      } else if (fvFaceCorrFunc.size() == 12) {
         factor *= fvFaceCorrFunc[group[iFace] * 3] ? TMath::Max(0., fvFaceCorrFunc[group[iFace] * 3]->Eval(ucor * sign[0][iFace])) : 1;
         factor *= fvFaceCorrFunc[group[iFace] * 3 + 1] ? TMath::Max(0., fvFaceCorrFunc[group[iFace] * 3 + 1]->Eval(vcor * sign[1][iFace])) : 1;
         factor *= fvFaceCorrFunc[group[iFace] * 3 + 2] ? TMath::Max(0., fvFaceCorrFunc[group[iFace] * 3 + 2]->Eval(wcor * sign[2][iFace])) : 1;
      } else {
         Report(R_WARNING, "Size of FaceCorrFunc, %d, is not expected.", (Int_t)fvFaceCorrFunc.size());
      }
      vFactor[iFace] = factor;
   }
   return vFactor;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::RecoverDeadChannel(Int_t iGamma, RecGamma* gamma)
{
   if (!GetPosition(iGamma, gamma)) {
      Report(R_WARNING, "Position of %d-th gamma is not found. Dead channel recovery is skipped.\n", iGamma);
      return;
   }

   // if (!fNphoEstimation->IsValid()) {
   //    Report(R_WARNING, "Npho cannot be estimated. Dead channel recovery is skipped.\n");
   //    return;
   // }

   GetPileupGamma();

   switch (gAnalyzer->GetXECEnePMWeightCorrection()->GetDeadChannelRecoveryFlag()) {
   case kRecoverFromTemplate :
      RecoverDeadChannelFromTemplate(gamma);
      break;
   case kRecoverFromSurroundingsSolidAngle :
      RecoverDeadChannelFromSurroundings(gamma);
      break;
   case kRecoverFromSurroundingsAverage :
      RecoverDeadChannelFromSurroundings(gamma);
      break;
   case kRecoverFromMLInpainting :
      RecoverDeadChannelFromMLInpainting(gamma);
      break;
   default :
      break;
   }

}

//______________________________________________________________________________
void MEGTXECEnePMWeight::RecoverDeadChannelFromTemplate(RecGamma* gamma)
{
   if (fNphoEstimation->UpdateInfo(gAnalyzer->GetCurrentRunNumber(), gAnalyzer->GetCurrentEventNumber())) {
      for (auto pm : gamma->fvPM) {
         fNphoEstimation->UpdatePM(pm->fIndex, pm->fNpho);
      }
   }

   std::vector<Int_t> vPMRejected = SelectPMRejected();
   if (!fNphoEstimation->EnergyFit(gamma->fXYZ, gamma->fEnergy, vPMRejected, true)) {
      Report(R_WARNING, "Energy fitting is invalid. Dead channel recovery is skipped.");
      return;
   }
   Float_t energy = fNphoEstimation->GetEnergyEstimated();

   std::map<Int_t, std::pair<Float_t, Float_t> > vPM;
   std::array<Float_t, 3> xyzSym, uvwSym;
   for (auto pm : gamma->fvPM) {
      if (pm->fInvalid) {
         vPM = fNphoEstimation->GetPMAtSymmetricPosition(pm->fIndex, pm->fPMRH);

         Int_t pmIndex(-1), nAdd(0);
         Float_t npho(0), nphoUncert(0), nphoAve(0);
         std::pair<Float_t, Float_t> sign;
         for (auto itr = vPM.begin(); itr != vPM.end(); itr++) {
            pmIndex = itr->first;
            sign = itr->second;
            PM* pm2 = gamma->FindPM(pmIndex);
            if (!pm2 || pm2->fInvalid) {
               continue;
            }

            xyzSym[0] = gamma->fXYZ[0];
            xyzSym[1] = sign.second * gamma->fXYZ[1];
            xyzSym[2] = sign.first  * gamma->fXYZ[2];
            uvwSym[0] = sign.first  * gamma->fUVW[0];
            uvwSym[1] = sign.second * gamma->fUVW[1];
            uvwSym[2] = gamma->fUVW[2];

            if (fNphoEstimation->EstimateNpho(pmIndex, xyzSym, uvwSym, energy, npho, nphoUncert)) {
               nphoAve += npho;
               nAdd++;
            }
         }

         if (nAdd) {
            nphoAve /= nAdd;
         }
         fNphoEstimation->LimitReplacement(pm->fIndex, pm->fPMRH->GetFace(), nphoAve);
      }
   }
   //copy to gamma
   for (auto pm : gamma->fvPM) {
      pm->fNphoEstimated = fNphoEstimation->GetNphoEstimatedAt(pm->fIndex);
      pm->fNphoEstimatedFlag = fNphoEstimation->GetNphoEstimatedFlagAt(pm->fIndex);
      pm->fNphoFit = fNphoEstimation->GetNphoFitAt(pm->fIndex);
   }

   Float_t nsum2Raw = 0;
   Float_t nsum2Recovered = 0;
   Float_t factor;
   for (auto pm : gamma->fvPM) {
      factor = pm->fCharge2Npho * pm->fSolidAngleCorr * pm->fFaceCorr;
      nsum2Raw += pm->fNpho * factor;
      nsum2Recovered += (pm->fNphoEstimatedFlag ? pm->fNphoEstimated : pm->fNpho) * factor;
   }
   for (auto pm : gamma->fvPM) {
      pm->fDeadCorr = nsum2Recovered / nsum2Raw;//constant enhancement
   }

}

//______________________________________________________________________________
void MEGTXECEnePMWeight::RecoverDeadChannelFromMLInpainting(RecGamma* gamma)
{
#ifdef HAVE_LIBTORCH
   if (!fInpainterModel) return;
   auto* model = static_cast<torch::jit::Module*>(fInpainterModel);

   const Int_t kNSensors = 4760;

   // 1. Build input (1, 4760, 2) with raw npho + relative time, and mask (1, 4760)
   // Time input is tpm relative to the earliest tpm among channels with nphe > 50,

   // Find min tpm over valid channels with nphe > 50
   Float_t minTpm = std::numeric_limits<Float_t>::max();
   for (auto pm : gamma->fvPM) {
      if (pm->fInvalid || pm->fPMRH->GetIsBad()) continue;
      auto* clus = gAnalyzer->GetXECPMClusterAt(pm->fIndex);
      if (gamma->fIndex >= clus->GettpmSize()) continue;
      Float_t nphe = gamma->fIndex < clus->GetnpheSize() ? clus->GetnpheAt(gamma->fIndex) : 0.f;
      Float_t tpm  = clus->GettpmAt(gamma->fIndex);
      if (nphe > 50.f && std::isfinite(tpm) && tpm < minTpm) minTpm = tpm;
   }
   if (minTpm == std::numeric_limits<Float_t>::max()) minTpm = 0.f;

   auto input = torch::zeros({1, kNSensors, 2});
   // auto mask = torch::zeros({1, kNSensors});
   auto mask = torch::ones({1, kNSensors});
   auto in_a = input.accessor<float, 3>();
   auto mk_a = mask.accessor<float, 2>();

   for (auto pm : gamma->fvPM) {
      Int_t i = pm->fIndex;
      if (i < 0 || i >= kNSensors) continue;

      if (pm->fInvalid || pm->fPMRH->GetIsBad()) {
         // mk_a[0][i] = 1.0f;  // masked
         // For time: average relative tpm of surrounding valid channels on same face
         Float_t tSum = 0; Int_t nV = 0;
         Float_t dThr = gAnalyzer->GetXECEnePMWeightCorrection()
                            ->GetDeadChannelRecoveryDistanceThreshold();
         for (auto jpm : gamma->fvPM) {
            if (jpm->fInvalid || jpm->fPMRH->GetIsBad()) continue;
            if (jpm->fPMRH->GetFace() != pm->fPMRH->GetFace()) continue;
            Double_t d = TMath::Sqrt(
               TMath::Power(pm->fPMRH->GetXYZAt(0)-jpm->fPMRH->GetXYZAt(0),2)+
               TMath::Power(pm->fPMRH->GetXYZAt(1)-jpm->fPMRH->GetXYZAt(1),2)+
               TMath::Power(pm->fPMRH->GetXYZAt(2)-jpm->fPMRH->GetXYZAt(2),2));
            if (d < dThr) {
               auto* jclus = gAnalyzer->GetXECPMClusterAt(jpm->fIndex);
               if (gamma->fIndex < jclus->GettpmSize()) {
                  tSum += jclus->GettpmAt(gamma->fIndex) - minTpm;
                  nV++;
               }
            }
         }
         in_a[0][i][0] = 0.f;  // npho placeholder (model uses sentinel via mask)
         in_a[0][i][1] = nV > 0 ? tSum / nV : 0.f;
      } else {
         mk_a[0][i] = 0.0f;
         in_a[0][i][0] = pm->fNpho;
         auto* clus = gAnalyzer->GetXECPMClusterAt(i);
         Float_t tpm = gamma->fIndex < clus->GettpmSize()
                       ? clus->GettpmAt(gamma->fIndex) : 0.f;
         in_a[0][i][1] = tpm - minTpm;
      }
   }
   // Sensors beyond nPM: mark as masked
   for (Int_t i = (Int_t)gamma->fvPM.size(); i < kNSensors; i++)
      mk_a[0][i] = 1.0f;

   // 2. Inference (model handles normalization internally)
   torch::NoGradGuard no_grad;
   auto output = model->forward({input, mask}).toTensor();  // (1, 4760)
   auto out_a = output.accessor<float, 2>();

   // 3. Set fNphoEstimated for dead channels
   for (auto pm : gamma->fvPM) {
      if (pm->fInvalid || pm->fPMRH->GetIsBad()) {
         Float_t npho = out_a[0][pm->fIndex];
         pm->fNphoEstimated = npho > 0 ? npho : 0;
         pm->fNphoEstimatedFlag = true;
      }
   }

   // 4. Compute fDeadCorr per face
   Float_t nface2Raw[XECCONSTANTS::kNumberOfFaces] = {0.};
   Float_t nface2Rec[XECCONSTANTS::kNumberOfFaces] = {0.};
   for (auto pm : gamma->fvPM) {
      Float_t f = pm->fPMRH->GetQsum2Weight() * pm->fSolidAngleCorr * pm->fFaceCorr;
      if (pm->fNpho >= 0) {
         nface2Raw[pm->fPMRH->GetFace()] += pm->fNpho * f;
      }
      if (pm->fNphoEstimatedFlag) {
         if (pm->fNphoEstimated > 0) {
            nface2Rec[pm->fPMRH->GetFace()] += pm->fNphoEstimated * f;
         }
      } else {
         if (pm->fNpho >= 0) {
            nface2Rec[pm->fPMRH->GetFace()] += pm->fNpho * f;
         }
      }
   }
   for (auto pm : gamma->fvPM) {
      if (nface2Raw[pm->fPMRH->GetFace()] > 0 && nface2Rec[pm->fPMRH->GetFace()] > 0) {
         pm->fDeadCorr = nface2Rec[pm->fPMRH->GetFace()] / nface2Raw[pm->fPMRH->GetFace()];
      } else {
         pm->fDeadCorr = 1.;
      }
   }
#else
   Report(R_ERROR, "ML inpainting (method 4) requires LibTorch. Rebuild with LIBTORCHSYS.");
#endif
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::RecoverDeadChannelFromSurroundings(RecGamma* gamma)
{
   // Check gamma position
   if (gamma->fXYZ[0] == XECTOOLS::kXECInvalidX
       || gamma->fXYZ[1] == XECTOOLS::kXECInvalidY
       || gamma->fXYZ[2] == XECTOOLS::kXECInvalidZ) {
      return;
   }

   //not implemented
   Double_t nphothreshold = gAnalyzer->GetXECEnePMWeightCorrection()->GetDeadChannelRecoveryNphoThreshold();
   for (auto pm : gamma->fvPM) {
      if (pm->fInvalid || pm->fPMRH->GetIsBad()) {

         // Int_t iPM = pm->fIndex;
         Double_t solidangle_surround = 0;
         Double_t npho_surround = 0;
         Int_t nsurround = 0;
         // Double_t npho_target = pm->fNpho;
         Double_t solidangle_target = GetSolidAngle(gamma->fXYZ, pm->fIndex);

         for (auto jpm : gamma->fvPM) {
            if (jpm->fPMRH->GetFace() != pm->fPMRH->GetFace() || jpm->fPMRH->GetIsBad()) {
               continue;
            }
            // if (TMath::Abs(pm->fPMRH->GetNumberInRow() - jpm->fPMRH->GetNumberInRow()) < 3 &&
            //     TMath::Abs(pm->fPMRH->GetRowInFace() - jpm->fPMRH->GetRowInFace()) < 3) {
            Double_t distance = TMath::Sqrt(TMath::Power(pm->fPMRH->GetXYZAt(0) - jpm->fPMRH->GetXYZAt(0), 2) +
                                            TMath::Power(pm->fPMRH->GetXYZAt(1) - jpm->fPMRH->GetXYZAt(1), 2) +
                                            TMath::Power(pm->fPMRH->GetXYZAt(2) - jpm->fPMRH->GetXYZAt(2), 2));
            if (distance < gAnalyzer->GetXECEnePMWeightCorrection()->GetDeadChannelRecoveryDistanceThreshold()) {
               Double_t solidangle = GetSolidAngle(gamma->fXYZ, jpm->fIndex);
               npho_surround += jpm->fNpho;
               solidangle_surround += solidangle;
               nsurround++;
            }
         }

         if (npho_surround > nphothreshold && gAnalyzer->GetXECEnePMWeightCorrection()->GetDeadChannelRecoveryFlag()==kRecoverFromSurroundingsSolidAngle) {
            pm->fNphoEstimated = npho_surround * solidangle_target / solidangle_surround;
            pm->fNphoEstimatedFlag = true;
         } else {
            pm->fNphoEstimated = npho_surround / nsurround;
            pm->fNphoEstimatedFlag = true;
         }
      }
   }

   Float_t factor;
   Float_t nface2Raw[kNumberOfFaces] = {0.};
   Float_t nface2Recovered[kNumberOfFaces] = {0.};
   for (auto pm : gamma->fvPM) {
      factor = pm->fPMRH->GetQsum2Weight() * pm->fSolidAngleCorr * pm->fFaceCorr;
      if (pm->fNpho >= 0) {
         nface2Raw[pm->fPMRH->GetFace()] += pm->fNpho * factor;
      }
      if (pm->fNphoEstimatedFlag) {
         if (pm->fNphoEstimated > 0) {
            nface2Recovered[pm->fPMRH->GetFace()] += pm->fNphoEstimated * factor;
         }
      } else {
         if (pm->fNpho >= 0) {
            nface2Recovered[pm->fPMRH->GetFace()] += pm->fNpho * factor;
         }
      }
   }
   for (auto pm : gamma->fvPM) {
      if (nface2Raw[pm->fPMRH->GetFace()] > 0 && nface2Recovered[pm->fPMRH->GetFace()] > 0) {
         pm->fDeadCorr = nface2Recovered[pm->fPMRH->GetFace()] / nface2Raw[pm->fPMRH->GetFace()];//constant enhancement
      } else {
         pm->fDeadCorr = 1.;
      }
   }
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::GetPileupGamma()
{
   if (fvPLGamma.size()) {
      return;
   }

   switch (GetSP()->GetPileupReference()) {
   case kPLFromPL :
      GetPileupGammaFromPL();
      break;
   case kPLFromPLCL :
   default:
      GetPileupGammaFromPLCL();
      break;
   case -1:
      break;
   }
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::GetPileupGammaFromPL()
{
   MEGXECPileupResult* pPLResult = gAnalyzer->GetXECPileupResult();
   if (!pPLResult) {
      Report(R_WARNING, "XECPileupResult is not found.");
      return;
   }

   PLGamma* gamma;
   std::array<Float_t, 3> uvw;
   const Int_t nPL = pPLResult->GetnpeakldInner();
   for (Int_t iPL = 1; iPL < nPL; iPL++) {
      //skip main gamma
      uvw[0] = pPLResult->GetupeakldInnerAt(iPL);
      uvw[1] = pPLResult->GetvpeakldInnerAt(iPL);
      uvw[2] = 0;

      gamma = new PLGamma(iPL);
      gamma->fUVW = uvw;
      fvPLGamma.push_back(gamma);
   }
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::GetPileupGammaFromPLCL()
{
   const Int_t nPL = gAnalyzer->GetXECPileupClusteringResultSize();
   if (!nPL) {
      Report(R_WARNING, "XECPileupClusteringResult is not found.");
      return;
   }

   PLGamma* gamma;
   std::array<Float_t, 3> uvw;
   MEGXECPileupClusteringResult* pPLCLResult;
   for (Int_t iPL = 1; iPL < nPL; iPL++) {
      //skip main gamma
      pPLCLResult = gAnalyzer->GetXECPileupClusteringResultAt(iPL);
      uvw[0] = pPLCLResult->Getupeak();
      uvw[1] = pPLCLResult->Getvpeak();
      uvw[2] = 0;

      gamma = new PLGamma(iPL);
      gamma->fUVW = uvw;
      fvPLGamma.push_back(gamma);
   }
}

//______________________________________________________________________________
std::vector<Int_t> MEGTXECEnePMWeight::SelectPMRejected()
{
   const Int_t nPM = gAnalyzer->GetXECRunHeader()->GetNPM();
   std::vector<Int_t> vPMIndex;
   // reject using timefit result
   if (gAnalyzer->GetXECTimeFitResultSize() >= 1) {
      for (Int_t iPM = 0; iPM < gAnalyzer->GetXECTimeFitResultAt(0)->GetvalidSize(); iPM++) {
         if (!gAnalyzer->GetXECTimeFitResultAt(0)->GetvalidAt(iPM)) {
            vPMIndex.push_back(iPM);
         }
      }
   }

   //reject channels around pileup
   const Float_t kEliminationRange = 20.94 * MEG::degree;//from MEG
   TVector3 plPos, pmPos;
   Double_t xyz[3];
   for (auto gamma : fvPLGamma) {
      plPos.SetXYZ(XECTOOLS::UVW2X(gamma->fUVW[0], gamma->fUVW[1], 0),
                   XECTOOLS::UVW2Y(gamma->fUVW[0], gamma->fUVW[1], 0),
                   XECTOOLS::UVW2Z(gamma->fUVW[0], gamma->fUVW[1], 0));

      for (Int_t iPM = 0; iPM < nPM; iPM++) {
         xyz[0] = gAnalyzer->GetXECPMRunHeaderAt(iPM)->GetXYZAt(0);
         xyz[1] = gAnalyzer->GetXECPMRunHeaderAt(iPM)->GetXYZAt(1);
         xyz[2] = gAnalyzer->GetXECPMRunHeaderAt(iPM)->GetXYZAt(2);
         pmPos.SetXYZ(xyz[0], xyz[1], xyz[2]);
         if (plPos.Angle(pmPos) * TMath::RadToDeg() < kEliminationRange) {
            vPMIndex.push_back(iPM);
         }
      }
   }

   //remove overlap
   std::sort(vPMIndex.begin(), vPMIndex.end());
   vPMIndex.erase(std::unique(vPMIndex.begin(), vPMIndex.end()), vPMIndex.end());

   return vPMIndex;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::CalcWeight(RecGamma* gamma)
{

   for (auto pm : gamma->fvPM) {
      pm->fWeight = 1.;
      pm->fWeight *= pm->fPMRH->GetQsum2Weight();
      // pm->fWeight *= pm->fCharge2Npho;
      pm->fWeight *= pm->fSolidAngleCorr;
      pm->fWeight *= pm->fFaceCorr;
      pm->fWeight *= pm->fDeadCorr;
   }

}

//______________________________________________________________________________
Bool_t MEGTXECEnePMWeight::GetPosition(Int_t iGamma, RecGamma* gamma)
{
   if (gamma->fPosFlag) {
      return true;
   }

   std::array<Float_t, 3> xyz, uvw;

   const Int_t posType = GetSP()->GetPositionType();
   switch (posType) {
   case kPosMCTruth:
      if (gAnalyzer->GetMCXECHitSize() > iGamma) {
         MEGMCXECHit* mcxechit = gAnalyzer->GetMCXECHitAt(iGamma);//<--could be consistent when iGamma > 0?
         xyz[0] = mcxechit->Getxyz1ConvAt(0);
         xyz[1] = mcxechit->Getxyz1ConvAt(1);
         xyz[2] = mcxechit->Getxyz1ConvAt(2);
         uvw[0] = XECTOOLS::XYZ2U(xyz[0], xyz[1], xyz[2]);
         uvw[1] = XECTOOLS::XYZ2V(xyz[0], xyz[1], xyz[2]);
         uvw[2] = XECTOOLS::XYZ2W(xyz[0], xyz[1], xyz[2]);
      } else {
         Report(R_WARNING, "Position cannot be read from MC.\n");
         return false;
      }
      break;
   case kPosMean:
      if (gAnalyzer->GetXECPosLocalFitResultSize() > iGamma) {
         uvw[0] = gAnalyzer->GetXECPosLocalFitResultAt(iGamma)->GetuvwmeanAt(0);
         uvw[1] = gAnalyzer->GetXECPosLocalFitResultAt(iGamma)->GetuvwmeanAt(1);
         uvw[2] = gAnalyzer->GetXECPosLocalFitResultAt(iGamma)->GetuvwmeanAt(2);
         xyz[0] = XECTOOLS::UVW2X(uvw[0], uvw[1], uvw[2]);
         xyz[1] = XECTOOLS::UVW2Y(uvw[0], uvw[1], uvw[2]);
         xyz[2] = XECTOOLS::UVW2Z(uvw[0], uvw[1], uvw[2]);
      } else {
         Report(R_WARNING, "Position cannot be read from PosLocalFitResult.\n");
         return false;
      }
      break;
   case kPosLocalFit:
      if (gAnalyzer->GetXECPosLocalFitResultSize() > iGamma) {
         uvw[0] = gAnalyzer->GetXECPosLocalFitResultAt(iGamma)->GetuvwAt(0);
         uvw[1] = gAnalyzer->GetXECPosLocalFitResultAt(iGamma)->GetuvwAt(1);
         uvw[2] = gAnalyzer->GetXECPosLocalFitResultAt(iGamma)->GetuvwAt(2);
         xyz[0] = XECTOOLS::UVW2X(uvw[0], uvw[1], uvw[2]);
         xyz[1] = XECTOOLS::UVW2Y(uvw[0], uvw[1], uvw[2]);
         xyz[2] = XECTOOLS::UVW2Z(uvw[0], uvw[1], uvw[2]);
      } else {
         Report(R_WARNING, "Position cannot be read from PosLocalFitResult.\n");
         return false;
      }
      break;
   default:
      Report(R_WARNING, "Position type %d is unknown. PosLocalFit is used instead.\n", posType);
      GetSP()->SetPositionType(kPosLocalFit);
      return GetPosition(iGamma, gamma);
      break;
   }

   gamma->fUVW = uvw;

   if (uvw[0] == XECTOOLS::kXECInvalidU ||
       uvw[1] == XECTOOLS::kXECInvalidV ||
       uvw[2] == XECTOOLS::kXECInvalidW) {
      // Invalid values directly filled instead of XECTOOLS::UVW2XYZ(invalid uvw).
      xyz[0] = XECTOOLS::kXECInvalidX;
      xyz[1] = XECTOOLS::kXECInvalidY;
      xyz[2] = XECTOOLS::kXECInvalidZ;
   }
   gamma->fXYZ = xyz;
   gamma->fPosFlag = true;

   return true;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::FillResult(RecGamma* gamma)
{

   MEGXECEnePMWeightResult* pEnePMWeightResult;
   for (auto pm : gamma->fvPM) {
      pEnePMWeightResult = gAnalyzer->GetXECEnePMWeightResultAt(pm->fIndex);

      pEnePMWeightResult->SetweightAt(gamma->fIndex, pm->fWeight);
      pEnePMWeightResult->Setcharge2nphoAt(gamma->fIndex, pm->fCharge2Npho);
      pEnePMWeightResult->SetsolidangleAt(gamma->fIndex, pm->fSolidAngle);
      pEnePMWeightResult->SetsolidanglecorrAt(gamma->fIndex, pm->fSolidAngleCorr);
      pEnePMWeightResult->SetfacecorrAt(gamma->fIndex, pm->fFaceCorr);
      pEnePMWeightResult->SetdeadcorrAt(gamma->fIndex, pm->fDeadCorr);
      pEnePMWeightResult->SetnphoAt(gamma->fIndex, pm->fNphoEstimatedFlag ? pm->fNphoEstimated : pm->fNpho);
      pEnePMWeightResult->SetnphorecoveredAt(gamma->fIndex, pm->fNphoEstimatedFlag);
      pEnePMWeightResult->SetnphofitAt(gamma->fIndex, pm->fNphoFit);
   }

}

//______________________________________________________________________________
void MEGTXECEnePMWeight::GetSolidAngleCorrFunc()
{
   MEGXECEnePMWeightCorrection *pCorrection = gAnalyzer->GetXECEnePMWeightCorrection();

   TString name = "fXECEnePMWeightSolidAngleCorrFunc";
   TString nameCoeff = "fXECEnePMWeightSolidAngleCorrFuncCoeff";
   TString formula;
   const Int_t nPar = pCorrection->GetSolidAngleCorrNPar();

   switch (pCorrection->GetSolidAngleCorrType()) {
   case kSolidAngleNoCorrection :
   default :
      break;
   case kSolidAngleCorrWithPol :
      formula.Form("pol%d", nPar);
      fSolidAngleCorrFunc = new TF1(name, formula, 0, 6);
      for (Int_t iPar = 0; iPar < nPar; iPar++) {
         fSolidAngleCorrFunc->SetParameter(iPar, pCorrection->GetSolidAngleCorrParAt(iPar));
      }

      fSolidAngleCorrFuncNorm = fSolidAngleCorrFunc->Eval(pCorrection->GetSolidAngleCorrNormAngle());
      break;
   case kSolidAngleCorrWithLog :
      fSolidAngleCorrFuncCoeff = new TF1(nameCoeff, "pol1", -5, 5);
      fSolidAngleCorrFuncCoeff->SetParameter(0, pCorrection->GetSolidAngleCorrParAt(0));
      fSolidAngleCorrFuncCoeff->SetParameter(1, pCorrection->GetSolidAngleCorrParAt(1));

      fSolidAngleCorrFunc = new TF1(name, "[0] + [1] * TMath::Log(x)", 0, 6);
      fSolidAngleCorrFunc->SetParameter(0, pCorrection->GetSolidAngleCorrParAt(2));
      fSolidAngleCorrFunc->SetParameter(1, fSolidAngleCorrFuncCoeff->Eval(pCorrection->GetSolidAngleCorrDepthBoundary()));

      fSolidAngleCorrFuncNorm = fSolidAngleCorrFunc->Eval(pCorrection->GetSolidAngleCorrNormAngle());
      break;
   }
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::GetFaceCorrFunc()
{
   MEGXECEnePMWeightCorrection *pCorrection = gAnalyzer->GetXECEnePMWeightCorrection();
   MEGXECEnePMWeightFaceCorrection *pFaceCorrection;

   const Int_t nFunc = pCorrection->GetFaceCorrNFunc();
   fvFaceCorrFunc.resize(nFunc, 0);

   for (Int_t iFunc = 0; iFunc < nFunc; iFunc++) {
      pFaceCorrection = gAnalyzer->GetXECEnePMWeightFaceCorrectionAt(iFunc);

      const Int_t nPar = pFaceCorrection->GetNPar();
      if (nPar) {
         fvFaceCorrFunc[iFunc] = new TF1(pFaceCorrection->GetFunctionName().Data()
                                         , pFaceCorrection->GetFunctionFormula().Data()
                                         , -100, 100);
         for (Int_t iPar = 0; iPar < nPar; iPar++) {
            fvFaceCorrFunc[iFunc]->SetParameter(iPar, pFaceCorrection->GetParAt(iPar));
         }
      }
   }
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::GetLDTemplateTable()
{
   MEGXECEnePMWeightCorrection *pCorrection = gAnalyzer->GetXECEnePMWeightCorrection();
   switch (GetSP()->GetLDTemplate()->GetType()) {
   case kLDReadFromDB:
   default:
      GetSP()->GetLDTemplate()->SetDirectoryPath("");
      GetSP()->GetLDTemplate()->SetFileName(pCorrection->GetLDTemplateTableFileName());
      break;
   case kLDReadFromFile:
      //nothing to do
      break;
   case 2:
      break;
   }

   TString name = Form("%s/%s"
                       , GetSP()->GetLDTemplate()->GetDirectoryPath().Data()
                       , GetSP()->GetLDTemplate()->GetFileName().Data());


   std::map<XECNphoEstimation::TableCacheKey, XECNphoEstimation*>::iterator cache;
   cache = XECNPHOESTIMATION::gvNphoEstimation.find(XECNphoEstimation::TableCacheKey(name));
   if (cache == XECNPHOESTIMATION::gvNphoEstimation.end()) {
      fNphoEstimation = new XECNphoEstimation();
      fNphoEstimation->UpdateTable(name);
      XECNPHOESTIMATION::gvNphoEstimation[XECNphoEstimation::TableCacheKey(name)] = fNphoEstimation;
   } else {
      fNphoEstimation = cache->second;
   }
}

//______________________________________________________________________________
Int_t MEGTXECEnePMWeight::GetMaxPMInner(const Int_t iGamma, std::vector<PM*>& vPM)
{
   Int_t maxPM = -1;
   if (gAnalyzer->GetXECFastRecResultSize() > iGamma) {
      maxPM = gAnalyzer->GetXECFastRecResultAt(iGamma)->Getinmaxcl();
   } else {
      Float_t maxNpho = 0;
      for (auto pm : vPM) {
         if (pm->fPMRH->GetFace() != XECCONSTANTS::kInnerFace) {
            continue;
         }
         if (pm->fInvalid) {
            continue;
         }
         if (maxNpho < pm->fNpho) {
            maxNpho = pm->fNpho;
            maxPM = pm->fIndex;
         }
      }
   }
   return maxPM;
}

//______________________________________________________________________________
Float_t MEGTXECEnePMWeight::GetGammaEnergy(const Int_t iGamma, std::vector<PM*>& vPM)
{
   Float_t energy = 0;
   if (gAnalyzer->GetXECFastRecResultSize() > iGamma) {
      energy = gAnalyzer->GetXECFastRecResultAt(iGamma)->Getenergy();
   } else {
      Float_t nsum2(0), ninner2(0);
      for (auto pm : vPM) {
         if (pm->fInvalid) {
            continue;
         }
         nsum2 += pm->fNpho;
         if (pm->fPMRH->GetFace() == XECCONSTANTS::kInnerFace) {
            ninner2 += pm->fNpho;
         }
      }
      // Is it OK to call the correction here??
      MEGXECEneTotalSumRecCorrection *pCorrection = gAnalyzer->GetXECEneTotalSumRecCorrection();
      MEGXECEneTotalSumRecScaleCorrection *pScaleCorrection;
      TString nsumType;
      for (Int_t iEne = 0; iEne < pCorrection->GetNEne(); iEne++) {
         pScaleCorrection = gAnalyzer->GetXECEneTotalSumRecScaleCorrectionAt(iEne);
         nsumType = pScaleCorrection->GetNsumType();
         nsumType.ToUpper();
         if (nsumType == "FASTREC" || nsumType == "ALL") {//<-- representative
            nsum2 = nsum2 + ninner2 * pScaleCorrection->GetInnerRatio();
            for (Int_t iDeg = 0; iDeg < pScaleCorrection->GetDegree(); iDeg++) {
               energy += TMath::Power(nsum2, iDeg) * pScaleCorrection->GetCoefAt(iDeg);
            }
            break;
         }
      }
   }

   return energy;
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::PrepareTemplate()
{
   Int_t nUBin = GetSP()->GetMakeTemplate()->GetNUBin();
   Int_t nVBin = GetSP()->GetMakeTemplate()->GetNVBin();
   Int_t nWBin = GetSP()->GetMakeTemplate()->GetNWBin();

   std::vector<Float_t> vUBinEdge, vVBinEdge, vWBinEdge;
   TObjArray *binArray = GetSP()->GetMakeTemplate()->GetUBinEdge().Tokenize(",");
   for (Int_t i = 0; i < binArray->GetEntries(); i++) {
      TObjString *binStr = (TObjString*)binArray->At(i);
      vUBinEdge.push_back(binStr->GetString().Atof());
   }
   delete binArray;
   binArray = GetSP()->GetMakeTemplate()->GetVBinEdge().Tokenize(",");
   for (Int_t i = 0; i < binArray->GetEntries(); i++) {
      TObjString *binStr = (TObjString*)binArray->At(i);
      vVBinEdge.push_back(binStr->GetString().Atof());
   }
   delete binArray;
   binArray = GetSP()->GetMakeTemplate()->GetWBinEdge().Tokenize(",");
   for (Int_t i = 0; i < binArray->GetEntries(); i++) {
      TObjString *binStr = (TObjString*)binArray->At(i);
      vWBinEdge.push_back(binStr->GetString().Atof());
   }
   delete binArray;

   if (nUBin < 0) {
      nUBin = vUBinEdge.size() - 1;
   }
   if (nVBin < 0) {
      nVBin = vVBinEdge.size() - 1;
   }
   if (nWBin < 0) {
      nWBin = vWBinEdge.size() - 1;
   }

   if (nUBin != (Int_t)vUBinEdge.size() - 1) {
      const Float_t lowerEdge = vUBinEdge[0];
      const Float_t higherEdge = vUBinEdge[vUBinEdge.size() - 1];
      vUBinEdge.clear();
      for (Int_t iBin = 0; iBin <= nUBin; iBin++) {
         vUBinEdge.push_back(lowerEdge + (higherEdge - lowerEdge) / nUBin * iBin);
      }
   }
   if (nVBin != (Int_t)vVBinEdge.size() - 1) {
      const Float_t lowerEdge = vVBinEdge[0];
      const Float_t higherEdge = vVBinEdge[vVBinEdge.size() - 1];
      vVBinEdge.clear();
      for (Int_t iBin = 0; iBin <= nVBin; iBin++) {
         vVBinEdge.push_back(lowerEdge + (higherEdge - lowerEdge) / nVBin * iBin);
      }
   }
   if (nWBin != (Int_t)vWBinEdge.size() - 1) {
      const Float_t lowerEdge = vWBinEdge[0];
      const Float_t higherEdge = vWBinEdge[vWBinEdge.size() - 1];
      vWBinEdge.clear();
      for (Int_t iBin = 0; iBin <= nWBin; iBin++) {
         vWBinEdge.push_back(lowerEdge + (higherEdge - lowerEdge) / nWBin * iBin);
      }
   }

   const Int_t nPM = gAnalyzer->GetXECRunHeader()->GetNPM();
   fLDTemplateTable = new XECLDTemplateTable();
   XECLDTemplate_PMInfo* pmInfo = new XECLDTemplate_PMInfo(nPM);
   XECLDTemplate* tmpl;
   for (Int_t iUBin = 0; iUBin < nUBin; iUBin++) {
      for (Int_t iVBin = 0; iVBin < nVBin; iVBin++) {
         for (Int_t iWBin = 0; iWBin < nWBin; iWBin++) {
            tmpl = new XECLDTemplate(pmInfo);
            tmpl->SetIndex(fLDTemplateTable->GetSize());
            tmpl->SetU((vUBinEdge[iUBin] + vUBinEdge[iUBin + 1]) / 2);
            tmpl->SetV((vVBinEdge[iVBin] + vVBinEdge[iVBin + 1]) / 2);
            tmpl->SetW((vWBinEdge[iWBin] + vWBinEdge[iWBin + 1]) / 2);
            tmpl->SetURange(vUBinEdge[iUBin], vUBinEdge[iUBin + 1]);
            tmpl->SetVRange(vVBinEdge[iVBin], vVBinEdge[iVBin + 1]);
            tmpl->SetWRange(vWBinEdge[iWBin], vWBinEdge[iWBin + 1]);
            fLDTemplateTable->AddLDTemplate(tmpl);
         }
      }
   }
   fLDTemplateTable->SortTable();
}

//______________________________________________________________________________
void MEGTXECEnePMWeight::AddTemplate(MEGTXECEnePMWeight::RecGamma* gamma)
{
   GetPileupGamma();
   if (fvPLGamma.size() > 0) {
      return;
   }

   const Int_t iGamma = gamma->fIndex;
   if (!GetPosition(iGamma, gamma)) {
      Report(R_WARNING, "Position of %d-th gamma is not found. Solid angle correction is skipped.\n", iGamma);
      return;
   }

   XECLDTemplate* tmpl = fLDTemplateTable->GetLDTemplate(gamma->fUVW);
   if (!tmpl) {
      return;
   }

   Float_t nsum2(0), ninner2(0), npmt2(0);
   if (gAnalyzer->GetXECFastRecResultSize() > iGamma) {
      nsum2 = gAnalyzer->GetXECFastRecResultAt(iGamma)->Getnsum2();
      ninner2 = gAnalyzer->GetXECFastRecResultAt(iGamma)->Getninner2();
      npmt2 = gAnalyzer->GetXECFastRecResultAt(iGamma)->Getnpmt2();
   } else {
      for (auto pm : gamma->fvPM) {
         if (pm->fInvalid) {
            continue;
         }
         nsum2 += pm->fNpho;
         if (pm->fPMRH->GetFace() == XECCONSTANTS::kInnerFace) {
            ninner2 += pm->fNpho;
         } else {
            npmt2 += pm->fNpho;
         }
      }
   }

   const Int_t nPM = gAnalyzer->GetXECRunHeader()->GetNPM();
   std::vector<Float_t> npho(nPM, 0);
   for (Int_t iPM = 0; iPM < nPM; iPM++) {
      PM* pm = gamma->FindPM(iPM);
      if (pm && !pm->fInvalid) {
         // npho[iPM] = pm->fNpho / TMath::Max((Float_t)1e-12, pm->fPMRH->GetIsSiPM() ? ninner2 : npmt2);
         npho[iPM] = pm->fNpho;
      }
   }

   tmpl->AddEvent(npho);
   tmpl->AddMPPCR(ninner2 / nsum2);

   return;
}
